# Resources/config/assets.yml
assets:

    wbw.syntaxhighlighter.asset.syntaxhighlighter:
        version: "3.0.83"
        brushes:
            - "AppleScript"
            - "AS3"
            - "Bash"
            - "ColdFusion"
            - "Cpp"
            - "CSharp"
            - "Css"
            - "Delphi"
            - "Diff"
            - "Erlang"
            - "Groovy"
            - "Java"
            - "JavaFX"
            - "JScript"
            - "Perl"
            - "Php"
            - "Plain"
            - "PowerShell"
            - "Python"
            - "Ruby"
            - "Sass"
            - "Scala"
            - "Sql"
            - "Vb"
            - "Xml"
        themes:
            - "Default"
            - "Django"
            - "Eclipse"
            - "Emacs"
            - "FadeToGrey"
            - "MDUltra"
            - "Midnight"
            - "RDark"
