# Resources/config/services.yml
services:

    webeweb.syntaxhighlighterbundle.provider.syntaxhighlighterstrings:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Provider\SyntaxHighlighterStringsProvider
        arguments: ["@translator"]

    webeweb.syntaxhighlighterbundle.twig.extension.syntaxhighlighter:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Twig\Extension\SyntaxHighlighterTwigExtension
        tags:
          - { name: "twig.extension" }
