# Resources/config/services.yml
services:

    webeweb.bundle.syntaxhighlighterbundle.twig.extension.syntaxhighlighter:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Twig\Extension\SyntaxHighlighterTwigExtension
        tags:
          - { name: "twig.extension" }
