# Resources/config/services.yml
services:

    webeweb.syntaxhighlighter.provider.syntaxhighlighter_strings:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Provider\SyntaxHighlighterStringsProvider
        arguments: ["@translator"]
        public:    true

    webeweb.syntaxhighlighter.twig.extension.syntaxhighlighter:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Twig\Extension\SyntaxHighlighterTwigExtension
        arguments: ["@twig"]
        public:    true
        tags:
            - { name: "twig.extension" }
