# Resources/config/services.yml
services:

    wbw.syntaxhighlighter.provider.syntaxhighlighter_strings:
        class:     WBW\Bundle\SyntaxHighlighterBundle\Provider\SyntaxHighlighterStringsProvider
        arguments: ["@translator"]
        public:    true
